apiVersion: apps/v1
kind: Deployment
metadata:
  name: compiler
  labels:
    app: compiler
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: compiler
  template:
    metadata:
      labels:
        app: compiler
    spec:
      containers:
        - name: {{.Values.image.name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: {{.Values.service.port}}
              protocol: TCP
