apiVersion: v1
kind: Service
metadata:
  name: comiler
  labels:
    app: compiler
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
  selector:
    app: compiler
